MGDSTRM-8261-Updating Admin server to use Quarkus 2.7.5 and smallrye-jwt 3.5.3
bf2fc6cc711aee1a0c2a/kafka-admin-api pull request #211
Opened 2022-07-12 18:58 UTC by biswassri

2022-07-12 19:07 UTC, MikeEdgar requested changes

2022-07-12 19:07 UTC, MikeEdgar commented on kafka-admin/pom.xml
> +            <version>2.7.5.Final</version>
Remove version

2022-07-12 19:14 UTC, MikeEdgar commented
We will also need to managed the smallrye-jwt version to the current version so that we can configure the OAuth trusted certificate similar to what was previously done in `TrustedSSOCallerPrincipalFactoryProducer`. To do this, set the value of `smallrye.jwt.client.tls.certificate` to `${kafka.admin.oauth.trusted.cert:}` in the application properties. The value will be provide by kas-fleetshard in the environment variables.

https://github.com/smallrye/smallrye-jwt/releases/tag/3.5.3

2022-07-12 19:29 UTC, biswassri commented on pom.xml
> +            </dependency>
Removal of this is giving me `The project org.bf2:kafka-admin:0.12.0-SNAPSHOT (/Users/srijoni/Desktop/Work/main/kafka-admin-api/kafka-admin/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for io.quarkus:quarkus-reactive-routes:jar is missing. @ line 237, column 21`

2022-07-13 12:59 UTC, MikeEdgar requested changes

2022-07-13 12:59 UTC, MikeEdgar commented on pom.xml
>          <smallrye-openapi.version>2.1.20</smallrye-openapi.version>
No longer needed with Quarkus 2.7.5, also remove `smallrye-open-api-core` from `dependencyManagement`
```suggestion
```

2022-07-13 12:59 UTC, MikeEdgar commented on pom.xml
>          <jandex.version>2.4.1.Final</jandex.version>
No longer needed with Quarkus 2.7.5, also remove `jandex` from `dependencyManagement`
```suggestion
```

2022-07-13 13:44 UTC, biswassri commented on pom.xml
> +                <artifactId>smallrye-jwt-build</artifactId>
oh sorry! Mistake.

2022-07-13 22:58 UTC, MikeEdgar approved these changes
LGTM :+1:

2022-07-14 16:28 UTC, rareddy approved these changes
lgtm

2022-07-14 19:58 UTC, merged